- hosts: [rhel8]
  become: yes
  gather_facts: no
  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_cis
    oscap_policy: ssg-rhel8-ds
  tasks:
  - name: install openscap scanner
    yum:
      name: 
        - openscap-scanner
        - scap-security-guide
      state: latest
    
  - block:
    - name: run openscap
      no_log: True
      command: >
        oscap xccdf eval
        --profile {{ oscap_profile }}
        --results-arf /tmp/oscap-arf.xml
        --report /tmp/oscap-report.html
        --fetch-remote-resources
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:
    - name: Generate remediation playbook
      command: >
        oscap xccdf generate fix 
        --fix-type ansible 
        --output /tmp/PlaybookToRemediate.yml 
        --result-id "" /tmp/oscap-arf.xml

    - name: download html report
      fetch:
        src: /tmp/oscap-report.html
        dest: ./{{ inventory_hostname }}.html
        flat: yes
    
    - name: download remediation playbook
      fetch:
        src: /tmp/PlaybookToRemediate.yml 
        dest: ./{{ inventory_hostname }}-Remediation.yml
        flat: yes